"""fresh create vault tables

Revision ID: a2c0da6cb4c0
Revises: 3b117d77f607
Create Date: 2026-05-04 23:42:23.315890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2c0da6cb4c0'
down_revision: Union[str, Sequence[str], None] = '3b117d77f607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # 1. Manual check and creation of the Enum type
    result = bind.execute(
        sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'docstatus')")
    )
    type_exists = result.scalar()

    if not type_exists:
        postgresql.ENUM('PENDING', 'VERIFIED', 'EXPIRED',
                        name='docstatus').create(bind)

    # 2. Create the Document table
    op.create_table(
        'document',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False),
        sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False),
        sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False),
        sa.Column('expiry_date', sa.DateTime(), nullable=True),
        # --- CRITICAL FIX: Use postgresql.ENUM with create_type=False ---
        sa.Column('status', postgresql.ENUM('PENDING', 'VERIFIED', 'EXPIRED',
                                            name='docstatus',
                                            create_type=False),  # This prevents the duplicate error
                  nullable=False),
        # ----------------------------------------------------------------
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # 3. Create the VaultShare table
    op.create_table(
        'vaultshare',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('professional_email',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('professional_type',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('shared_docs', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaultshare')
    op.drop_table('document')

    # Drop the Enum type
    bind = op.get_bind()
    postgresql.ENUM(name='docstatus').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
