"""global_schema_update

Revision ID: a7e0b0d753b5
Revises: a9756bdb10ab
Create Date: 2026-02-21 19:49:06.055009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7e0b0d753b5'
down_revision: Union[str, Sequence[str], None] = 'a9756bdb10ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Manually create the ENUM types first
    # This prevents the "type does not exist" error
    property_type_enum = sa.Enum(
        'APARTMENT', 'HOUSE', 'VILLA', 'COMMERCIAL', name='propertytype')
    area_unit_enum = sa.Enum('SQM', 'SQFT', name='areaunit')

    property_type_enum.create(op.get_bind(), checkfirst=True)
    area_unit_enum.create(op.get_bind(), checkfirst=True)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countryrule', sa.Column('country_name',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('countryrule', sa.Column('currency_code',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('countryrule', sa.Column('currency_symbol',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('countryrule', sa.Column(
        'min_down_payment_pct', sa.Float(), nullable=False))
    op.add_column('countryrule', sa.Column(
        'tax_rate_pct', sa.Float(), nullable=False))
    op.add_column('countryrule', sa.Column(
        'additional_fees_fixed', sa.Float(), nullable=False))
    op.drop_column('countryrule', 'tax_rate')
    op.add_column('property', sa.Column('property_type', sa.Enum(
        'APARTMENT', 'HOUSE', 'VILLA', 'COMMERCIAL', name='propertytype'), nullable=False))
    op.add_column('property', sa.Column(
        'currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('property', sa.Column('area', sa.Float(), nullable=True))
    op.add_column('property', sa.Column('area_unit', sa.Enum(
        'SQM', 'SQFT', name='areaunit'), nullable=False))
    op.add_column('property', sa.Column('country_code',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('property', sa.Column(
        'source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_property_country_code'),
                    'property', ['country_code'], unique=False)
    op.drop_column('property', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('country', sa.VARCHAR(),
                  autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_property_country_code'), table_name='property')
    op.drop_column('property', 'source_url')
    op.drop_column('property', 'country_code')
    op.drop_column('property', 'area_unit')
    op.drop_column('property', 'area')
    op.drop_column('property', 'currency')
    op.drop_column('property', 'property_type')
    op.add_column('countryrule', sa.Column('tax_rate', sa.DOUBLE_PRECISION(
        precision=53), autoincrement=False, nullable=False))
    op.drop_column('countryrule', 'additional_fees_fixed')
    op.drop_column('countryrule', 'tax_rate_pct')
    op.drop_column('countryrule', 'min_down_payment_pct')
    op.drop_column('countryrule', 'currency_symbol')
    op.drop_column('countryrule', 'currency_code')
    op.drop_column('countryrule', 'country_name')

    # 3. Then drop the ENUM types
    sa.Enum(name='propertytype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='areaunit').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
