"""add_favorites_link_table

Revision ID: a9756bdb10ab
Revises: c4881df3fb8a
Create Date: 2026-02-20 13:52:34.675384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9756bdb10ab'
down_revision: Union[str, Sequence[str], None] = 'c4881df3fb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfavorite',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('property_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['property_id'], ['property.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'property_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userfavorite')
    # ### end Alembic commands ###
