"""added_scraper_fields_to_property

Revision ID: adabd3461a06
Revises: a7e0b0d753b5
Create Date: 2026-02-25 23:52:26.470358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'adabd3461a06'
down_revision: Union[str, Sequence[str], None] = 'a7e0b0d753b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # 1. Manually create the ENUM types first
    # This prevents the "type does not exist" error
    property_type_enum = sa.Enum(
        'APARTMENT', 'HOUSE', 'VILLA', 'COMMERCIAL', name='propertytype')
    area_unit_enum = sa.Enum('SQM', 'SQFT', name='areaunit')

    property_type_enum.create(op.get_bind(), checkfirst=True)
    area_unit_enum.create(op.get_bind(), checkfirst=True)

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column(
        'external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('property', sa.Column(
        'source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('property', sa.Column(
        'description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property', sa.Column('rooms', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column(
        'bathrooms', sa.Integer(), nullable=True))
    op.add_column('property', sa.Column('location_province',
                  sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property', sa.Column(
        'address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property', sa.Column(
        'zip_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property', sa.Column(
        'video_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property', sa.Column(
        'tour_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property', sa.Column(
        'agency_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property', sa.Column(
        'updated_at', sa.DateTime(), nullable=False))
    op.alter_column('property', 'property_type',
                    existing_type=postgresql.ENUM(
                        'APARTMENT', 'HOUSE', 'VILLA', 'COMMERCIAL', name='propertytype'),
                    type_=sqlmodel.sql.sqltypes.AutoString(),
                    existing_nullable=False)
    op.alter_column('property', 'location_city',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('property', 'latitude',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.alter_column('property', 'longitude',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=True)
    op.create_index(op.f('ix_property_external_id'),
                    'property', ['external_id'], unique=True)
    op.create_index(op.f('ix_property_source'),
                    'property', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_source'), table_name='property')
    op.drop_index(op.f('ix_property_external_id'), table_name='property')
    op.alter_column('property', 'longitude',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('property', 'latitude',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('property', 'location_city',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('property', 'property_type',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(),
                    type_=postgresql.ENUM(
                        'APARTMENT', 'HOUSE', 'VILLA', 'COMMERCIAL', name='propertytype'),
                    existing_nullable=False)
    op.drop_column('property', 'updated_at')
    op.drop_column('property', 'agency_name')
    op.drop_column('property', 'tour_url')
    op.drop_column('property', 'video_url')
    op.drop_column('property', 'zip_code')
    op.drop_column('property', 'address')
    op.drop_column('property', 'location_province')
    op.drop_column('property', 'bathrooms')
    op.drop_column('property', 'rooms')
    op.drop_column('property', 'description')
    op.drop_column('property', 'source')
    op.drop_column('property', 'external_id')
    # 3. Then drop the ENUM types
    sa.Enum(name='propertytype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='areaunit').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
