"""initial_schema

Revision ID: c4881df3fb8a
Revises: 
Create Date: 2026-02-20 12:39:44.988396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4881df3fb8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countryrule',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('tax_rate', sa.Float(), nullable=False),
                    sa.Column('lending_multiplier',
                              sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('country_code')
                    )
    op.create_table('property',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column(
                        'country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('location_city',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=False),
                    sa.Column('longitude', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column(
                        'email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('hashed_password',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('financialprofile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('annual_income', sa.Float(), nullable=False),
                    sa.Column('total_savings', sa.Float(), nullable=False),
                    sa.Column('monthly_debt', sa.Float(), nullable=False),
                    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financialprofile')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('property')
    op.drop_table('countryrule')
    # ### end Alembic commands ###
